import Head from "next/head";

export default function Home() {
  return (
    <>
      <Head>
        <title>Uguumur Messenger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="w-full h-screen bg-slate-100 flex flex-col justify-between items-center px-40 py-20">
        <div className="w-full flex flex-col gap-2">
          <div className="w-full bg-sky-400 px-4 py-4 font-bold rounded-t-lg rounded-l-lg text-slate-100">
            Hi, Yu bna daaa
          </div>
          <div className="w-full bg-sky-400 px-4 py-4 font-bold rounded-t-lg rounded-l-lg text-slate-100">
            Twan doo
          </div>
          <div className="w-full bg-sky-400 px-4 py-4 font-bold rounded-t-lg rounded-l-lg text-slate-100">
            ene hen bicheed bnaa?
          </div>
        </div>
        <div className="w-full flex justify-between">
          <input
            type="text"
            placeholder="chat here..."
            className="w-full px-4 py-1 rounded"
          />
          <button className="px-4 py-1 bg-sky-400 text-slate-100 rounded hover:bg-sky-300">
            Илгээх
          </button>
        </div>
      </div>
    </>
  );
}
